version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: victor
          POSTGRES_DB: adonis_api_test

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo npm install -g @adonisjs/cli
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build-and-deploy-on-hold:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev-victor

      - test:
          requires:
            - build

      - hold:
          type: approval
          requires:
            - test

      - deploy-development:
          requires:
            - test
            - build
          filters:
            branches:
              only: dev-victor

      - deploy-prod:
          requires:
            - build
            - test
            - hold
          filters:
            branches:
              only: master
